# This Module is to validate the sql query generated by the llms
import re
from backend.src.utils.app_logger import logger

class QueryValidationError(Exception):
    pass

    
FORBIDDEN_KEYWORDS = {
    "INSERT", "UPDATE", "DELETE", "DROP",
    "ALTER", "TRUNCATE", "CREATE",
    "GRANT", "REVOKE"
    }

def query_validation(mysql_query:str):
    logger.info("SQL validation started")
    if not mysql_query:
        raise QueryValidationError("Empty Query")
    
    #re.sub(pattern, replacement, string)
    query=re.sub(r"(--.*) | (#.*) | (/*\[\s\S]*?\*/)","",mysql_query).strip().rstrip(";")
    upper_cased_query=query.upper()
    try:
        if not upper_cased_query.startswith("SELECT"):
            raise QueryValidationError("Invalid Query, does not starts with 'SELECT'")
    
        if ";" in upper_cased_query[:-1]:
            raise QueryValidationError("Multiple sql statements are not allowed")
    
        for keyword in FORBIDDEN_KEYWORDS:
            if re.search(rf"\b{keyword}\b", upper_cased_query):
                raise QueryValidationError(f"Forbidden keyword detected: {keyword}")
    except QueryValidationError:
        logger.exception("Unsafe SQL %s", query)
        raise   
    except Exception as e:
        logger.exception(e) 
        raise
    
    logger.info("SQL Query is validated %s", query)
    return query

if __name__=="__main__":
    result=query_validation(mysql_query="select * from database;")
    print(result)
    
    
#python -m backend.src.data_fetch.sql_guard

